"""October 2026 IG/FB static batch (4-31 Oct, 08:00 + 12:00). Built 1 Oct 2026.
Scores are (downloads, engagement, conversion, relatability), 1-10, Chuby's bar. Ship at 8+ avg (task rule); target 9+.
"""
SEND = [  # (note, thanks, highlight word, caption hook, scores)
 ("you still make my tea exactly how I like it.", "thank you for noticing.", "exactly", "Send this to the one who knows your tea order by heart.", (8, 9, 8, 10)),
 ("you warm the car up before I leave.", "I see it. Every frosty morning.", "warm", "Frosty mornings, defrosted windscreen. Send this to them.", (8, 9, 8, 10)),
 ("you remember which one is my mug.", "small thing. Huge to me.", "my mug", "There's a mug in your house that only one person uses. Send this.", (8, 9, 8, 10)),
 ("you text me when you get there. Every time.", "it means more than you know.", "Every time.", "'Home safe x' is a love language. Send this to them.", (8, 9, 8, 10)),
 ("you always save me the last biscuit.", "that's love. Don't argue.", "last biscuit", "Sacrificing the last biscuit is the most romantic thing in Britain.", (8, 10, 8, 10)),
 ("you listen to the same work story twice.", "and still act surprised. Thank you.", "twice", "Tag the person who's heard about your colleague more times than they'd like.", (8, 10, 8, 10)),
 ("you put the heating on before I got home.", "I noticed. I always notice.", "heating", "Coming home to a warm house hits different. Send this.", (8, 9, 8, 9)),
 ("you let me have the good side of the bed.", "I'm keeping it. But thank you.", "good side", "There's a good side of the bed and you know who has it.", (8, 10, 8, 10)),
 ("you cooked when I'd had a rubbish day.", "I didn't say it enough. Thank you.", "rubbish day", "For the one who made tea and dinner without being asked. Send this.", (8, 9, 8, 10)),
 ("you remember my annoying colleague's name.", "that's how I know you listen.", "listen", "They know every character in your work drama. Send this to them.", (8, 10, 8, 10)),
 ("you still hold my hand in the car park.", "after all this time.", "still", "Some things don't wear off. Send this to them.", (8, 9, 8, 9)),
 ("you check the weather so I bring a coat.", "I never do. But I love that you try.", "a coat", "'Take a coat.' 'I'm fine.' Send this to your personal weather service.", (8, 10, 8, 10)),
 ("you queue for the takeaway so I don't have to.", "an actual hero. Thank you.", "hero", "Friday night heroes don't wear capes. They queue at the chippy.", (8, 9, 8, 9)),
 ("you still say goodnight like you mean it.", "because you do. I know you do.", "goodnight", "Send this to them before bed tonight.", (8, 9, 8, 9)),
 ("you charge my phone when I forget.", "which is always. Thank you.", "always", "5% battery, plugged in by someone who loves you. Send this.", (8, 10, 8, 10)),
 ("you laugh at my terrible jokes.", "even the ones you've heard 40 times.", "terrible", "Tag the person who still laughs at that joke.", (8, 10, 8, 10)),
 ("you plan the little dates so I don't have to.", "I owe you. Officially.", "I owe you.", "For the planner in your relationship. Send this to them.", (8, 9, 9, 9)),
 ("you never let me walk home alone.", "I feel safe with you. Always.", "alone", "Send this to the one who always walks you home.", (8, 9, 8, 9)),
 ("you defrost the dinner I forgot about.", "you save us every week. Thank you.", "forgot", "Every house has a dinner saviour. Send this to yours.", (8, 9, 8, 10)),
 ("you make Sundays feel like Sundays.", "slow mornings with you are my favourite.", "Sundays", "Send this to the one who makes Sunday mornings the best part of the week.", (8, 9, 8, 10)),
]

MATCH = [  # (5 pairs, foot, caption hook, scores)
 ([("Tea","Coffee"),("Stay in","Go out"),("Text","Call"),("Early bird","Night owl"),("Plan it","Wing it")], "Settle who owes who in CoupleIn.", "Both comment your letters. How many did you match?", (8, 10, 8, 9)),
 ([("Chippy","Curry"),("Big spoon","Little spoon"),("Heating on","Jumper on"),("Sunrise","Sunset"),("Cats","Dogs")], "Loser books the next date in the CoupleIn calendar.", "Heating on or jumper on? This one ends relationships.", (8, 10, 8, 10)),
 ([("Pub","Restaurant"),("Board game","Video game"),("Gym","Sofa"),("Summer","Winter"),("Sweet","Savoury")], "Winner's pick goes on the CoupleIn wishlist.", "Comment your 5 letters, then make them do it too.", (8, 10, 8, 9)),
 ([("Toast","Cereal"),("Road trip","Flight"),("Pizza","Burger"),("Messy","Tidy"),("Hug","Kiss")], "Settle who owes who in CoupleIn.", "Messy or tidy says a lot. Comment your letters.", (8, 10, 8, 9)),
 ([("Roast","Fry-up"),("Ketchup","Brown sauce"),("Gravy","No gravy"),("Yorkshires","Stuffing"),("Mash","Roasties")], "Loser cooks Sunday dinner. Diary it in CoupleIn.", "The most British compatibility test ever made.", (8, 10, 8, 10)),
 ([("Lie-in","Early start"),("Pasta","Rice"),("Marvel","Rom-com"),("Jeans","Joggers"),("Cosy pub","Cocktail bar")], "Winner's pick goes on the CoupleIn wishlist.", "Both comment. No copying their answers.", (8, 9, 8, 9)),
 ([("Say sorry","Get space"),("Talk now","Talk later"),("Text it","Face to face"),("Hug it out","Walk it off"),("Forgive","Forget")], "Mismatched? CoupleIn helps you hear each other out.", "How you fight matters more than what you fight about. Compare your answers.", (8, 9, 9, 10)),
 ([("Halloween","Bonfire Night"),("Pumpkin spice","Hot choc"),("Horror","Comedy"),("Candles","Fairy lights"),("Rain","Snow")], "Plan your autumn dates in the CoupleIn calendar.", "Autumn edition. Comment your letters and count the matches.", (8, 10, 8, 9)),
 ([("Flowers","Snacks"),("Surprise","Planned"),("Gift","Experience"),("Words","Actions"),("Note","Text")], "Find your love language in 60 seconds. Link in bio.", "This is secretly a love language test. Then take the real one, link in bio.", (8, 9, 9, 10)),
 ([("Spender","Saver"),("Early","Just in time"),("Pack light","Pack it all"),("Satnav","Ask someone"),("Book ahead","Turn up")], "Settle who owes who in CoupleIn.", "Opposites attract. Until it's time to leave the house.", (8, 10, 8, 10)),
 ([("Dishwasher","Hand wash"),("Bins","Hoover"),("Cook","Wash up"),("Iron","Never iron"),("Make bed","Leave it")], "Log who did what in CoupleIn. Brownie Points count.", "Chores edition. Comment, then show them the scoreboard.", (8, 10, 9, 10)),
 ([("Scary film","Cosy film"),("Sweet popcorn","Salty popcorn"),("Sofa","Cinema"),("Subtitles","No subtitles"),("Phone down","Phone out")], "Loser picks up the snacks. Put it on the CoupleIn wishlist.", "Film night will never be the same. Comment your letters.", (8, 10, 8, 9)),
 ([("Quiet night","Party"),("House","Flat"),("City","Countryside"),("Garden","Balcony"),("Car","Train")], "Plan the dream in the CoupleIn calendar.", "Are you building the same life? Comment and compare.", (8, 9, 8, 9)),
 ([("Cuddle","Own space"),("Pyjamas","Onesie"),("Socks on","Socks off"),("Fan on","Fan off"),("Duvet hog","Duvet saint")], "Settle who owes who in CoupleIn.", "Bedtime edition. Who's the duvet hog? Be honest.", (8, 10, 8, 10)),
 ([("Voice note","Text"),("Call","FaceTime"),("Emoji","Words"),("Reply fast","Reply later"),("Long text","One word")], "Find your love language in 60 seconds. Link in bio.", "'k.' Compare your texting styles in the comments.", (8, 10, 8, 10)),
 ([("Bake","Buy"),("Spicy","Mild"),("Starter","Dessert"),("Same order","Different"),("Share food","Hands off")], "Winner's pick goes on the CoupleIn wishlist.", "Share food or hands off? Comment your letters.", (8, 10, 8, 10)),
 ([("Beach","Ski"),("Hotel","Airbnb"),("Plan it all","Go with it"),("Pool","Sea"),("Souvenirs","Photos")], "Put the next trip in the CoupleIn calendar.", "Holiday edition. Could you travel together?", (8, 10, 8, 9)),
 ([("Dance","Sofa"),("Cocktail","Pint"),("Home by 11","Out till 3"),("Kebab","Toastie"),("Taxi","Night bus")], "Settle who owes who in CoupleIn.", "Saturday night edition. Comment your letters.", (8, 10, 8, 9)),
 ([("Lights off","Lamp on"),("Window open","Window shut"),("Alarm","Snooze"),("Shower am","Shower pm"),("Breakfast","Skip it")], "Mismatched? Log the little compromises in CoupleIn.", "Living together edition. How many did you match?", (8, 10, 8, 10)),
 ([("Christmas","Birthday"),("Mountains","Seaside"),("Takeaway","Cook"),("Brunch","Dinner date"),("Sing","Hum")], "Winner's pick goes on the CoupleIn wishlist.", "Comment your letters. 5/5 gets a wedding invite.", (8, 9, 8, 9)),
]

PICK = [  # (4 outcomes, caption hook, scores)
 (["Your partner owes you a cuddle. They don't know yet.","Pick the next date. No veto.","You get the last bite. Of anything.","You were right. They have to say it out loud."], "Pick a card, then tag your partner. No take-backs.", (8, 10, 8, 9)),
 (["Breakfast in bed. This weekend.","They do the washing up for a week.","You choose the film. No complaints.","A 10-minute back rub, on demand."], "1, 2, 3 or 4? Swipe, then tag them so they can't 'forget'.", (8, 10, 8, 9)),
 (["They pay for the next takeaway.","You get the remote all evening.","They plan a surprise date this month.","A lie-in. They do the morning."], "Pick one. Tag them. It's binding.", (8, 10, 8, 9)),
 (["They write you a proper love note.","You skip one chore. Any chore.","They make you a hot chocolate tonight.","You pick the next holiday spot."], "Pick a card before you swipe.", (8, 10, 8, 9)),
 (["They owe you a dance in the kitchen.","Hoovering is theirs this week.","Your playlist in the car. All month.","One 'you were right', with a smile."], "Pick 1-4, swipe, then show them.", (8, 10, 8, 9)),
 (["They cook your favourite meal.","You get the warm side of the bed.","They do the next big shop.","A full day where you plan nothing."], "Comment your number and tag the person who owes you.", (8, 10, 8, 9)),
 (["They book a table somewhere new.","You win the next argument. Automatically.","They make the tea for a week.","A long walk, phones in pockets."], "Pick a card. Card 2 is dangerous.", (8, 10, 8, 10)),
 (["They name 3 things they love about you.","You choose dinner every night this week.","They run you a bath tonight.","Your next wishlist item. Their treat."], "Pick, swipe, tag. They'll pretend they didn't see it.", (8, 10, 9, 9)),
 (["They organise date night. Fully.","Bins are theirs until Christmas.","You get a no-questions nap.","They say 'I love you' first all week."], "Card 2 could change your life. Pick one.", (8, 10, 8, 10)),
 (["They bring you a coffee in bed.","You get the last slice. Always.","They book the cinema. You pick the film.","A whole evening in charge of the sofa."], "Pick a number. Tag them. Collect.", (8, 10, 8, 9)),
 (["They draw you a bath with candles.","You choose the weekend plan.","They clean the car for you.","A whole day of being right."], "Pick 1, 2, 3 or 4. No changing your answer.", (8, 10, 8, 9)),
 (["They make your lunch tomorrow.","You choose Sunday's roast.","They warm the car up all week.","A foot rub. No time limit."], "Pick a card. Comment your number.", (8, 10, 8, 9)),
 (["They write 5 things they love about you.","A free pass on one chore.","They make pancakes this weekend.","They take you somewhere new."], "Pick, then tag the person who's paying up.", (8, 10, 8, 9)),
 (["They take the photos. As many as you want.","You choose the takeaway. Forever.","They iron your outfit for a week.","Cuddles on demand. Any time."], "Pick a card. Swipe. Collect your prize.", (8, 10, 8, 10)),
 (["They plan a day you'll love.","Breakfast made all weekend.","They tidy your side of the room.","30 extra minutes in bed. Every day."], "1, 2, 3 or 4? Tag them before they can argue.", (8, 10, 8, 9)),
 (["They carve the pumpkin. You supervise.","You pick the scary film. No hiding.","They answer the door to trick-or-treaters.","First dibs on the sweets."], "Halloween edition. Pick a card, then tag them.", (8, 10, 8, 10)),
]
